In [82]:
import pandas as pd
import numpy as np
import seaborn as sns

In [83]:
train=pd.read_csv(r"C:\Users\anvay\Downloads\98efc33085a711eb\dataset\train.csv")
test=pd.read_csv(r"C:\Users\anvay\Downloads\98efc33085a711eb\dataset\test.csv")

In [84]:

for i in ['age', 'days_since_last_login', 'avg_time_spent','avg_transaction_value', 'points_in_wallet', 'churn_risk_score']:
    q3,q1=np.percentile(train[i],[75,25])
    iqr=q3-q1
    iqrmin=q1-(1.5*iqr)
    iqrmax=q3+(1.5*iqr)
    countsmin=train.loc[(train[i]<=iqrmin)].index
    countsmax=train.loc[(train[i]>=iqrmax)].index
    train.drop(countsmin,inplace=True,axis=0)
    train.drop(countsmax,inplace=True,axis=0)

In [85]:
train.loc[(train['avg_time_spent']>=0)&(train['avg_time_spent']<500)&(train['points_in_wallet'].isnull()==True),['points_in_wallet']]=300.05139
train.loc[(train['avg_time_spent']>=500)&(train['avg_time_spent']<1000)&(train['points_in_wallet'].isnull()==True),['points_in_wallet']]= 701.87
train.loc[(train['avg_time_spent']>=1000)&(train['avg_time_spent']<1500)&(train['points_in_wallet'].isnull()==True),['points_in_wallet']]=1135.268196

In [86]:
filters1=train.loc[train['points_in_wallet'].isnull()==True].index
train.drop(filters1,axis=0,inplace=True)

In [87]:
def fillNan(df, col, value):
    df[col].fillna(value, inplace=True)

In [88]:
fillNan(train, 'preferred_offer_types', train['preferred_offer_types'].mode()[0])
fillNan(test, 'preferred_offer_types', train['preferred_offer_types'].mode()[0])

In [89]:
fillNan(train, 'region_category', train['region_category'].mode()[0])
fillNan(test, 'region_category', test['region_category'].mode()[0])

In [90]:
test.loc[(test['avg_time_spent']>=0)&(test['avg_time_spent']<500)&(test['points_in_wallet'].isnull()==True),['points_in_wallet']]=300.05139
test.loc[(test['avg_time_spent']>=500)&(test['avg_time_spent']<1000)&(test['points_in_wallet'].isnull()==True),['points_in_wallet']]= 701.87
test.loc[(test['avg_time_spent']>=1000)&(test['avg_time_spent']<1500)&(test['points_in_wallet'].isnull()==True),['points_in_wallet']]=1135.268196

In [91]:
fillNan(test, 'points_in_wallet', test['points_in_wallet'].mode()[0])

In [92]:
test['churn_risk_score']=np.nan
train['data']='train'
test['data']='test'
all=pd.concat([train,test],axis=0)

In [93]:
all.drop(['security_no','Name','customer_id'],inplace=True,axis=1)

In [94]:
all.loc[(all['referral_id']!='xxxxxxxx') & (all['joined_through_referral']=='?'),['joined_through_referral']]='Yes'
all.loc[(all['referral_id']=='xxxxxxxx') & (all['joined_through_referral']=='?'),['joined_through_referral']]='No'

In [95]:
all.drop(['referral_id'],inplace=True,axis=1)

In [96]:
all.loc[all['points_in_wallet']<=0,['points_in_wallet']]=all.loc[all['points_in_wallet']<=0,['points_in_wallet']]*-1

In [97]:
all['days_since_last_login']=all['days_since_last_login'].replace(-999,0)

In [98]:
all.loc[all['avg_time_spent']<=0,['avg_time_spent']]=all.loc[all['avg_time_spent']<=0,['avg_time_spent']]*-1

In [99]:
all.loc[(all['avg_time_spent']>=0)&(all['avg_time_spent']<500)&(all['points_in_wallet'].isnull()==True),['points_in_wallet']]=302.493777
all.loc[(all['avg_time_spent']>=500)&(all['avg_time_spent']<1000)&(all['points_in_wallet'].isnull()==True),['points_in_wallet']]= 701.335
all.loc[(all['avg_time_spent']>=1000)&(all['avg_time_spent']<1500)&(all['points_in_wallet'].isnull()==True),['points_in_wallet']]=1127.511161

In [100]:
#filters1=all.loc[all['points_in_wallet'].isnull()==True].index
#all.drop(filters1,axis=0,inplace=True)
#filters2=all.loc[all['preferred_offer_types'].isnull()==True].index
#all.drop(filters2,axis=0,inplace=True)

In [101]:
all.isnull().sum()

age                                 0
gender                              0
region_category                     0
membership_category                 0
joining_date                        0
joined_through_referral             0
preferred_offer_types               0
medium_of_operation                 0
internet_option                     0
last_visit_time                     0
days_since_last_login               0
avg_time_spent                      0
avg_transaction_value               0
avg_frequency_login_days            0
points_in_wallet                    0
used_special_discount               0
offer_application_preference        0
past_complaint                      0
complaint_status                    0
feedback                            0
churn_risk_score                19919
data                                0
dtype: int64

In [102]:
all.loc[all['region_category'].isnull()==True,'region_category']='Village'

In [103]:
all['churn_risk_score']=all['churn_risk_score'].replace(-1,1)

In [104]:
train.describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,churn_risk_score
count,28659.000000,28659.000000,28659.000000,28659.000000,28659.000000,28659.000000
mean,37.128232,12.871628,206.510043,27276.882125,652.374416,3.675041
std,15.886823,5.558992,181.334862,16326.831781,213.279391,1.127670
min,10.000000,1.000000,-384.009123,804.340000,-549.357498,1.000000
25%,23.000000,9.000000,63.055000,13721.415000,580.530000,3.000000
50%,37.000000,13.000000,150.910000,26614.350000,680.190000,4.000000
75%,51.000000,17.000000,301.020000,39468.670000,754.120000,5.000000
max,64.000000,26.000000,801.290000,80670.670000,2069.069761,5.000000

In [105]:
all.isnull().sum()

age                                 0
gender                              0
region_category                     0
membership_category                 0
joining_date                        0
joined_through_referral             0
preferred_offer_types               0
medium_of_operation                 0
internet_option                     0
last_visit_time                     0
days_since_last_login               0
avg_time_spent                      0
avg_transaction_value               0
avg_frequency_login_days            0
points_in_wallet                    0
used_special_discount               0
offer_application_preference        0
past_complaint                      0
complaint_status                    0
feedback                            0
churn_risk_score                19919
data                                0
dtype: int64

In [106]:
for i in ['used_special_discount','offer_application_preference','past_complaint','joined_through_referral']:
    all[i]=all[i].replace('Yes',1)
    all[i]=all[i].replace('No',0)

In [107]:
all.drop(['last_visit_time'],axis=1,inplace=True)

In [108]:
all['joining_date'] = pd.to_datetime(all['joining_date'])
all['days_since_joined'] = all['joining_date'].apply(lambda x:(pd.Timestamp('today') - x).days)
all.drop(['joining_date'], inplace=True, axis=1)

train.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,data
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,...,53005.25,17.0,781.75000,Yes,Yes,No,Not Applicable,Products always in Stock,2,train
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,...,12838.38,10.0,300.05139,Yes,No,Yes,Solved,Quality Customer Care,1,train
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,...,21027.00,22.0,500.69000,No,Yes,Yes,Solved in Follow-up,Poor Website,5,train
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,...,25239.56,6.0,567.66000,No,Yes,Yes,Unsolved,Poor Website,5,train
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,...,24483.66,16.0,663.06000,No,Yes,Yes,Solved,Poor Website,5,train

In [109]:
for col in ['complaint_status','feedback','internet_option','region_category','gender','medium_of_operation','preferred_offer_types','membership_category']:
    temp=pd.get_dummies(all[col],prefix=col,drop_first=True)
    all=pd.concat([temp,all],1)
    all.drop([col],1,inplace=True)

In [110]:
all['avg_frequency_login_days']=all['avg_frequency_login_days'].replace('Error',0)

In [111]:
all['avg_frequency_login_days']=pd.to_numeric(all['avg_frequency_login_days'])

In [112]:
all.loc[all['avg_frequency_login_days']<0,'avg_frequency_login_days']=all.loc[all['avg_frequency_login_days']<0,'avg_frequency_login_days']*-1

In [113]:
feature=all.columns
num=all[feature].select_dtypes(include=['int64','float64','uint8']).columns
num

Index(['membership_category_Gold Membership',
       'membership_category_No Membership',
       'membership_category_Platinum Membership',
       'membership_category_Premium Membership',
       'membership_category_Silver Membership',
       'preferred_offer_types_Gift Vouchers/Coupons',
       'preferred_offer_types_Without Offers', 'medium_of_operation_Both',
       'medium_of_operation_Desktop', 'medium_of_operation_Smartphone',
       'gender_M', 'gender_Unknown', 'region_category_Town',
       'region_category_Village', 'internet_option_Mobile_Data',
       'internet_option_Wi-Fi', 'feedback_Poor Customer Service',
       'feedback_Poor Product Quality', 'feedback_Poor Website',
       'feedback_Products always in Stock', 'feedback_Quality Customer Care',
       'feedback_Reasonable Price', 'feedback_Too many ads',
       'feedback_User Friendly Website', 'complaint_status_Not Applicable',
       'complaint_status_Solved', 'complaint_status_Solved in Follow-up',
       'complaint_status_Unsolved', 'age', 'joined_through_referral',
       'days_since_last_login', 'avg_time_spent', 'avg_transaction_value',
       'avg_frequency_login_days', 'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'churn_risk_score',
       'days_since_joined'],
      dtype='object')

In [114]:
for i in ['membership_category_Gold Membership',
       'membership_category_No Membership',
       'membership_category_Platinum Membership',
       'membership_category_Premium Membership',
       'membership_category_Silver Membership',
       'preferred_offer_types_Gift Vouchers/Coupons',
       'preferred_offer_types_Without Offers', 'medium_of_operation_Both',
       'medium_of_operation_Desktop', 'medium_of_operation_Smartphone',
       'gender_M', 'gender_Unknown', 'region_category_Town',
       'region_category_Village', 'internet_option_Mobile_Data',
       'internet_option_Wi-Fi', 'feedback_Poor Customer Service',
       'feedback_Poor Product Quality', 'feedback_Poor Website',
       'feedback_Products always in Stock', 'feedback_Quality Customer Care',
       'feedback_Reasonable Price', 'feedback_Too many ads',
       'feedback_User Friendly Website', 'complaint_status_Not Applicable',
       'complaint_status_Solved', 'complaint_status_Solved in Follow-up',
       'complaint_status_Unsolved', 'age', 'joined_through_referral',
       'days_since_last_login', 'avg_time_spent', 'avg_transaction_value',
       'avg_frequency_login_days', 'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'churn_risk_score']:
    counts=all.loc[all[i]<0,i].count()
    print(i,'-',counts)

membership_category_Gold Membership - 0
membership_category_No Membership - 0
membership_category_Platinum Membership - 0
membership_category_Premium Membership - 0
membership_category_Silver Membership - 0
preferred_offer_types_Gift Vouchers/Coupons - 0
preferred_offer_types_Without Offers - 0
medium_of_operation_Both - 0
medium_of_operation_Desktop - 0
medium_of_operation_Smartphone - 0
gender_M - 0
gender_Unknown - 0
region_category_Town - 0
region_category_Village - 0
internet_option_Mobile_Data - 0
internet_option_Wi-Fi - 0
feedback_Poor Customer Service - 0
feedback_Poor Product Quality - 0
feedback_Poor Website - 0
feedback_Products always in Stock - 0
feedback_Quality Customer Care - 0
feedback_Reasonable Price - 0
feedback_Too many ads - 0
feedback_User Friendly Website - 0
complaint_status_Not Applicable - 0
complaint_status_Solved - 0
complaint_status_Solved in Follow-up - 0
complaint_status_Unsolved - 0
age - 0
joined_through_referral - 0
days_since_last_login - 0
avg_time_spent - 0
avg_transaction_value - 0
avg_frequency_login_days - 0
points_in_wallet - 0
used_special_discount - 0
offer_application_preference - 0
past_complaint - 0
churn_risk_score - 0

In [115]:
all.dtypes

membership_category_Gold Membership              uint8
membership_category_No Membership                uint8
membership_category_Platinum Membership          uint8
membership_category_Premium Membership           uint8
membership_category_Silver Membership            uint8
preferred_offer_types_Gift Vouchers/Coupons      uint8
preferred_offer_types_Without Offers             uint8
medium_of_operation_Both                         uint8
medium_of_operation_Desktop                      uint8
medium_of_operation_Smartphone                   uint8
gender_M                                         uint8
gender_Unknown                                   uint8
region_category_Town                             uint8
region_category_Village                          uint8
internet_option_Mobile_Data                      uint8
internet_option_Wi-Fi                            uint8
feedback_Poor Customer Service                   uint8
feedback_Poor Product Quality                    uint8
feedback_Poor Website                            uint8
feedback_Products always in Stock                uint8
feedback_Quality Customer Care                   uint8
feedback_Reasonable Price                        uint8
feedback_Too many ads                            uint8
feedback_User Friendly Website                   uint8
complaint_status_Not Applicable                  uint8
complaint_status_Solved                          uint8
complaint_status_Solved in Follow-up             uint8
complaint_status_Unsolved                        uint8
age                                              int64
joined_through_referral                          int64
days_since_last_login                            int64
avg_time_spent                                 float64
avg_transaction_value                          float64
avg_frequency_login_days                       float64
points_in_wallet                               float64
used_special_discount                            int64
offer_application_preference                     int64
past_complaint                                   int64
churn_risk_score                               float64
data                                            object
days_since_joined                                int64
dtype: object

In [116]:
train=all[all['data']=='train']
test=all[all['data']=='test']

In [117]:
del train['data']
test.drop(['churn_risk_score','data'],axis=1,inplace=True)

C:\Users\anvay\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [118]:
train.head()

,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Both,medium_of_operation_Desktop,medium_of_operation_Smartphone,...,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,churn_risk_score,days_since_joined
0,0,0,1,0,0,1,0,0,0,0,...,17,300.63,53005.25,17.0,781.75000,1,1,0,2.0,1319
1,0,0,0,1,0,1,0,0,1,0,...,16,306.34,12838.38,10.0,300.05139,1,0,1,1.0,1308
2,0,1,0,0,0,1,0,0,1,0,...,14,516.16,21027.00,22.0,500.69000,0,1,1,5.0,1598
3,0,1,0,0,0,1,0,0,1,0,...,11,53.27,25239.56,6.0,567.66000,0,1,1,5.0,1611
4,0,1,0,0,0,0,0,0,0,1,...,20,113.13,24483.66,16.0,663.06000,0,1,1,5.0,1293

In [119]:
test.head()

,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Both,medium_of_operation_Desktop,medium_of_operation_Smartphone,...,joined_through_referral,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,days_since_joined
0,0,0,0,1,0,0,1,0,0,1,...,0,12,386.26,40721.44,7.0,733.830000,1,0,0,1973
1,1,0,0,0,0,0,1,0,1,0,...,0,11,37.80,9644.40,9.0,726.000000,1,0,0,1853
2,0,0,0,0,1,1,0,1,0,0,...,0,18,215.36,3693.25,21.0,713.780000,1,0,1,1486
3,0,0,0,0,1,0,0,0,0,0,...,1,0,44.57,36809.56,11.0,744.970000,1,0,1,1318
4,0,1,0,0,0,0,1,0,0,1,...,1,6,349.88,40675.86,8.0,299.048351,0,1,1,2154

In [120]:
train.to_csv("prep_train2new1.csv",index=False)
test.to_csv("prep_test2new1.csv",index=False)